### ISSUE TITLE
Feature Request: Add CLI option to echo IMDB ID with title

### ISSUE THREAD

**Issue by garrettben** [SpaceK33z/plex2netflix#14]
I read your latest response on Issue #3 and thought it might be a simple add and handy feature for debugging.

**Comment by SpaceK33z** [comment]
Good idea, that will help surely help debugging and should be easy to implement.

**Comment by SpaceK33z** [comment]
Added a `--show-imdb` argument for this.

Released in `0.3.0`.

**Comment by garrettben** [comment]
Works great!  All of my movies that fail on "Invalid response" get an IMDB ID.  Thanks for adding.
