### ISSUE TITLE
lodash@4.17.2 causes error due to _.findWhere

### ISSUE THREAD

**Issue by garrettben** [SpaceK33z/plex2netflix#21]
_.findWhere was removed from lodash in [4.0.0](https://github.com/lodash/lodash/wiki/Changelog#v400)

Causes the following error:

plex2netflix -t <TOKEN> -s SomeLibrary
Successfully connected to Plex.
TypeError: _.findWhere is not a function

**Comment by SpaceK33z** [comment]
Would you be interested in filing a PR? I'm not actively using this project but will merge PR's.

**Comment by garrettben** [comment]
submitted.  Hopefully it doesn't suck.  :)

**Comment by manbearpig2012** [comment]
had this yesterday when i installed, was able to find a pre 4.0 version, was called `lodash_node` IIRC, and installed it alongside `lodash` and everything worked.... when i check lodash version still says above 4.0

**Comment by garrettben** [comment]
I just submitted a PR for it.  Hopefully doesn't break anything else.

**Comment by garrettben** [comment]
Does it need a version bump to get the fix to npm?

**Comment by SpaceK33z** [comment]
Yeah, I'll do that soon.

**Comment by SpaceK33z** [comment]
Released with `plex2netflix@0.5.0`. Sorry for the delay! I wanted to fix some additional things, see the [release page](https://github.com/SpaceK33z/plex2netflix/releases/tag/v0.5.0).
