### ISSUE TITLE
Error with non-asci characters in title

### ISSUE THREAD

**Issue by Undeadllama** [SpaceK33z/plex2netflix#26]
Running into an issue where movies with non-asci characters in their title causes plex2netflix to end with the following error:

`TypeError: Cannot read property 'title' of undefined`

In the output I see for example:

`???????? (1989) - nope`

Looking at the movies that were processed directly prior, and filtering by 1989, I figured this was most likely to be the movie Castle in the Sky. The original title contained "天空の城ラピュタ" within Plex.

I removed this original title within Plex, leaving just "Castle in the Sky" in place as the movie name.
Once I reran plex2netflix again I hit the same issue with another movie, this time Caché:

```
???????? (2005) - nope
TypeError: Cannot read property 'title' of undefined
```

I'm assuming this is due to the accent on the e.

Up until I see that particular error plex2netflix is running fine and is producing nope or yes results for movies successfully. It seems to just be getting hung up on a few movie titles along the way.

plex2netflix v0.5.0
node.js v6.10.0 LTS
Windows Server 2012 R2

**Comment by SpaceK33z** [comment]
This should be fixed now, let me know if it still produces errors.

**Comment by Undeadllama** [comment]
Looking good, many thanks!
