### ISSUE TITLE
SSL Error in Script

### ISSUE THREAD

**Issue by hikarukujo** [SpaceK33z/plex2netflix#30]
I get a certificate error for each query request when I run the script now. Looks like the SSL for https://webduck.nl/plex2netflix/search expired in late September. I changed it to http but it looks like there's a redirect to force https which just kicks in instead.

As best as I can tell the got command used can't ignore invalid SSL or I'd flip that on for testing, looking like the only fix is to renew the SSL?

**Comment by SpaceK33z** [comment]
Thanks for your bug report, I've fixed the SSL error! Turns out my Let's Encrypt auto-renewal script still doesn't automatically restart nginx.
