### ISSUE TITLE
404 error accessing your search proxy

### ISSUE THREAD

**Issue by khaosx** [SpaceK33z/plex2netflix#32]
Running the script generates a 404 error on every title. Manually going to https://webduck.nl/plex2netflix/search also results in a 404. Any advice?

**Comment by SpaceK33z** [comment]
Ah good point, I forgot to fix this when refactoring my website recently. I will look into it soon™️.

**Comment by kdog0598** [comment]
I am also having this issue.

**Comment by CardcaptorRLH85** [comment]
I just wanted to toss in a "me too" here.  I just ran this script for the first time and I'm having this same issue.

**Comment by nwithan8** [comment]
Same. You got mentioned in a MakeUseOf article, so you might have a couple new people complaining about this soon.
https://www.makeuseof.com/tag/best-plex-plugins-power-users/

**Comment by jack-thomas** [comment]
@nwithan8 Yep, I'm here because of the MakeUseOf article

**Comment by Jonathan34** [comment]
too bad I was really looking forward to freeing my disks

**Comment by colonelkrud** [comment]
The server that this is attempting to talk to is [here](https://github.com/SpaceK33z/plex2netflix-server). You can host your own and change the [url here](https://github.com/SpaceK33z/plex2netflix/blob/1dbe5f5dac02ba4043ff4f1fff192ef86eeaaa69/lib/apis/plex2netflix-server.js#L7) to point to your own server. This is a bit of a hack though. It is worth note that the API is not free either. You can find [pricing information here](https://market.mashape.com/unogs/unogs/pricing) if you are considering hosting your own copy. Keep in mind this is PER REQUEST. That means that if you have 10k files to scan, you will make 10k requests to the API. The caching only helps if you are being a nice person and hosting something public or running the same command multiple times as the server checks the cache before making an API request to UnoGs.

**Comment by nwithan8** [comment]
@colonelkrud Already tried it last night, but not really worth it. @SpaceK33z replied to me on Twitter that he hasn't forgotten about it.

**Comment by SpaceK33z** [comment]
Hi, the server is up and should work again! Be sure to use `plex2netflix@0.5.2`.

Thanks for linking to the MakeUseOf article, that explains all the sudden interest 😃.

Sorry it took so long, in my last sea of free time I've been focusing on [web-to-plex](https://github.com/SpaceK33z/web-to-plex), which also might interest you.
