### ISSUE TITLE
This worked quite good until some weeks ago. Will there ever be an update?

### ISSUE THREAD

**Issue by pven** [SpaceK33z/plex2netflix#34]
See subject :-)

**Comment by pven** [comment]
I dived a bit in the code and found that https://plex2netflix.now.sh/search is working with json. When I use the mentioned parameters, it looks like nothing is returned and finally I end up with a timeout.

**Comment by pven** [comment]
You can try by yourself: https://plex2netflix.now.sh/search?imdb=tt0083944

I never get a respons on that.

**Comment by pven** [comment]
When I wait long enoug, I get:

502: An error occurred with your deployment
Code: BAD_GATEWAY (more)

**Comment by SpaceK33z** [comment]
Just to give an update: the external provider I'm using to get the IMDB -> Netflix data is currently unavailable for me and I have emailed them to request access again.

Subscribe to this thread to get a notification when it's fixed.

**Comment by SpaceK33z** [comment]
Fixed!
