### ISSUE TITLE
Scan all libraries option, or multiple libraries

### ISSUE THREAD

**Issue by Ackis** [SpaceK33z/plex2netflix#4]
Right now we have the required option to specify a library to search through.

I'd like to see the ability to specify "All" to scan all the libraries available, or an option to specify multiple libraries to scan.

**Comment by SpaceK33z** [comment]
Yeah multiple libraries would definitely be nice.

An option to scan all libraries is also possible I think. I would need to filter out the libraries that are not for TV shows or movies though.

**Comment by SpaceK33z** [comment]
This has been implemented in version `0.2.2`.
